; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define <8 x i16> @vhaddw_h_b(<16 x i8> %a, <16 x i8> %b) nounwind {
; CHECK-LABEL: vhaddw_h_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vhaddw.h.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <16 x i8> %a, <16 x i8> poison,
                     <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>

  %1 = shufflevector <16 x i8> %b, <16 x i8> poison,
                     <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>

  %2 = sext <8 x i8> %0 to <8 x i16>
  %3 = sext <8 x i8> %1 to <8 x i16>

  %4 = add <8 x i16> %2, %3
  ret <8 x i16> %4
}

define <4 x i32> @vhaddw_w_h(<8 x i16> %a, <8 x i16> %b) nounwind {
; CHECK-LABEL: vhaddw_w_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vhaddw.w.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <8 x i16> %a, <8 x i16> poison,
                     <4 x i32> <i32 1, i32 3, i32 5, i32 7>

  %1 = shufflevector <8 x i16> %b, <8 x i16> poison,
                     <4 x i32> <i32 0, i32 2, i32 4, i32 6>

  %2 = sext <4 x i16> %0 to <4 x i32>
  %3 = sext <4 x i16> %1 to <4 x i32>

  %4 = add <4 x i32> %2, %3
  ret <4 x i32> %4
}

define <2 x i64> @vhaddw_d_w(<4 x i32> %a, <4 x i32> %b) nounwind {
; CHECK-LABEL: vhaddw_d_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vhaddw.d.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <4 x i32> %a, <4 x i32> poison, <2 x i32> <i32 1, i32 3>
  %1 = shufflevector <4 x i32> %b, <4 x i32> poison, <2 x i32> <i32 0, i32 2>

  %2 = sext <2 x i32> %0 to <2 x i64>
  %3 = sext <2 x i32> %1 to <2 x i64>

  %4 = add <2 x i64> %2, %3
  ret <2 x i64> %4
}

define <8 x i16> @vhaddw_hu_bu(<16 x i8> %a, <16 x i8> %b) nounwind {
; CHECK-LABEL: vhaddw_hu_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vhaddw.hu.bu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <16 x i8> %a, <16 x i8> poison,
                     <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>

  %1 = shufflevector <16 x i8> %b, <16 x i8> poison,
                     <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>

  %2 = zext <8 x i8> %0 to <8 x i16>
  %3 = zext <8 x i8> %1 to <8 x i16>

  %4 = add <8 x i16> %2, %3
  ret <8 x i16> %4
}

define <4 x i32> @vhaddw_wu_hu(<8 x i16> %a, <8 x i16> %b) nounwind {
; CHECK-LABEL: vhaddw_wu_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vhaddw.wu.hu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <8 x i16> %a, <8 x i16> poison,
                     <4 x i32> <i32 1, i32 3, i32 5, i32 7>

  %1 = shufflevector <8 x i16> %b, <8 x i16> poison,
                     <4 x i32> <i32 0, i32 2, i32 4, i32 6>

  %2 = zext <4 x i16> %0 to <4 x i32>
  %3 = zext <4 x i16> %1 to <4 x i32>

  %4 = add <4 x i32> %2, %3
  ret <4 x i32> %4
}

define <2 x i64> @vhaddw_du_wu(<4 x i32> %a, <4 x i32> %b) nounwind {
; CHECK-LABEL: vhaddw_du_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vhaddw.du.wu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <4 x i32> %a, <4 x i32> poison, <2 x i32> <i32 1, i32 3>
  %1 = shufflevector <4 x i32> %b, <4 x i32> poison, <2 x i32> <i32 0, i32 2>

  %2 = zext <2 x i32> %0 to <2 x i64>
  %3 = zext <2 x i32> %1 to <2 x i64>

  %4 = add <2 x i64> %2, %3
  ret <2 x i64> %4
}
