; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define <16 x i16> @vsllwil_h_b(<32 x i8> %a) nounwind {
; CHECK-LABEL: vsllwil_h_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsllwil.h.b $xr0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <32 x i8> %a, <32 x i8> poison,
                     <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7,
                                i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  %1 = sext <16 x i8> %0 to <16 x i16>
  %2 = shl nsw <16 x i16> %1, splat (i16 1)
  ret <16 x i16> %2
}

define <8 x i32> @vsllwil_w_h(<16 x i16> %a) nounwind {
; CHECK-LABEL: vsllwil_w_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsllwil.w.h $xr0, $xr0, 15
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <16 x i16> %a, <16 x i16> poison,
                     <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
  %1 = sext <8 x i16> %0 to <8 x i32>
  %2 = shl nsw <8 x i32> %1, splat (i32 15)
  ret <8 x i32> %2
}

define <4 x i64> @vsllwil_d_w(<8 x i32> %a) nounwind {
; CHECK-LABEL: vsllwil_d_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsllwil.d.w $xr0, $xr0, 31
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <8 x i32> %a, <8 x i32> poison,
                     <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %1 = sext <4 x i32> %0 to <4 x i64>
  %2 = shl nsw <4 x i64> %1, splat (i64 31)
  ret <4 x i64> %2
}

define <16 x i16> @vsllwil_hu_bu(<32 x i8> %a) nounwind {
; CHECK-LABEL: vsllwil_hu_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsllwil.hu.bu $xr0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <32 x i8> %a, <32 x i8> poison,
                     <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7,
                                i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  %1 = zext <16 x i8> %0 to <16 x i16>
  %2 = shl nsw <16 x i16> %1, splat (i16 1)
  ret <16 x i16> %2
}

define <8 x i32> @vsllwil_wu_hu(<16 x i16> %a) nounwind {
; CHECK-LABEL: vsllwil_wu_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsllwil.wu.hu $xr0, $xr0, 15
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <16 x i16> %a, <16 x i16> poison,
                     <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
  %1 = zext <8 x i16> %0 to <8 x i32>
  %2 = shl nsw <8 x i32> %1, splat (i32 15)
  ret <8 x i32> %2
}

define <4 x i64> @vsllwil_du_wu(<8 x i32> %a) nounwind {
; CHECK-LABEL: vsllwil_du_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsllwil.du.wu $xr0, $xr0, 31
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <8 x i32> %a, <8 x i32> poison,
                     <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %1 = zext <4 x i32> %0 to <4 x i64>
  %2 = shl nsw <4 x i64> %1, splat (i64 31)
  ret <4 x i64> %2
}
